#!/bin/bash

readonly THIS_CMD="${0##*/}"
readonly VERSION="0.0.1"
readonly LICENSE="MIT"
readonly GITHUB_URL="https://github.com"
readonly AUTHOR="sheepla"

readonly KEYBINDINGS="\
Ctrl+O   open with browser
Enter    view README"

function _version() {
	cat <<EOS
${THIS_CMD} v${VERSION}
released under the ${LICENSE} license.
    Author: ${AUTHOR} (${GITHUB_URL}/${AUTHOR})
EOS
}

function _help() {
	cat <<EOS
${THIS_CMD} -- GitHub repository browser with fzf

USAGE
    ${THIS_CMD} KEYWORDS...
    ${THIS_CMD} -h|--help
    ${THIS_CMD} -V|--version
EOS
}

function _main() {

	if [[ "${#}" -le 0 ]]; then
		_help
		_err "Must require arguments..."
		return 1
	fi

	for arg in "${@}"; do
		case "${arg}" in
		-h | --help)
			_help
			return 0
			;;
		-V | --version)
			_version
			return 0
			;;
		esac
	done

	_search_repo "${*}" | _fzf
}

function _err() {
	printf "[\e[31m ERR \e[m] %s\n" "${*}"
}

function _encode() {
	echo -n "${*}" | od -tx1 -An | tr ' ' % | tr -d \\n
}

function _search_repo() {
	local query
	query="$(_encode "${*}")"

	gh api \
		--header "Accept: application/vnd.github.v3+json" \
		--jq ".items[].full_name" \
		"search/repositories?q=${query}"
}

function _fzf() {
	fzf </dev/stdin \
		--multi \
		--header "${KEYBINDINGS}" \
		--preview "gh repo view {}" \
		--bind "enter:execute(gh repo view {})" \
		--bind "ctrl-o:execute(gh repo view {} -w)"
}

_main "${@}"
exit "${?}"
