#!/bin/bash

readonly THIS_CMD="${0##*/}"
readonly VERSION="0.0.1"
readonly LICENSE="MIT"
readonly AUTHOR="sheepla"

function _version() {
	cat <<EOS
${THIS_CMD} v${VERSION}
released under the ${LICENSE} license.
    Author: ${AUTHOR} (${BASE}/sheepla)
EOS
}

function _help() {
	cat <<EOS
${THIS_CMD} -- GitHub repository browser with fzf

USAGE
    ${THIS_CMD} KEYWORDS...
    ${THIS_CMD} -h|--help
    ${THIS_CMD} -V|--version
EOS
}

function _main() {

	if [[ "${#}" -le 0 ]]; then
		_help
		_err "Must require arguments..."
		return 1
	fi

	for arg in "${@}"; do
		case "${arg}" in
		-h | --help)
			_help
			return 0
			;;
		-V | --version)
			_version
			return 0
			;;
		esac
	done

	_search_repo "${*}" | _fzf
}

function _err() {
	printf "[\e[31m ERR \e[m] %s\n" "${*}"
}

function _encode() {
	echo -n "${*}" | od -tx1 -An | tr ' ' % | tr -d \\n
}

function _search_repo() {
	local query
	query="$(_encode "${*}")"

	gh api \
		--header "Accept: application/vnd.github.v3+json" \
		"search/repositories?q=${query}" |
		jq -r ".items[].full_name"
}

function _fzf() {
    readonly HEADER_MSG="\
Press Ctrl+R to view README
Press Enter to open the repository in your default browser"

	fzf </dev/stdin \
		--multi \
        --header-lines=1 \
        --header "${HEADER_MSG}" \
		--preview "gh repo view {}" \
		--bind "enter:execute(gh repo view -w {})" \
		--bind "ctrl-r:execute(gh repo view {})"
}

_main "${@}"
exit "${?}"
